
[env:main]
platform = espressif32@6.3.2
board = esp32doit-devkit-v1
framework = arduino
upload_speed = 460800
monitor_speed = 115200
;board_build.partitions = medspiffs_ota.csv
monitor_filters = esp32_exception_decoder
build_type = debug
lib_compat_mode = strict
lib_ldf_mode = deep
build_flags =
;	-D ARDUINOOTA
;	-D N2K
;	-D UM982
	-D WTRTK
	-D WEBSERIAL
	-D ELEGANTOTA
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
lib_deps = 
	https://github.com/ESP32Async/AsyncTCP#v3.4.9
	https://github.com/ESP32Async/ESPAsyncWebServer#v3.8.1
	https://github.com/wjquigs11/NMEA0183
;	ttlappalainen/NMEA2000-library@4.21.5
;	ttlappalainen/NMEA2000_esp32
;	https://github.com/ayushsharma82/WebSerial
	/home/wjquigs/nfs/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
;	/Users/wjquigs/mnt/nfs/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
;	/mnt/nfs/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
	https://github.com/ayushsharma82/ElegantOTA

[env:main-ota]
extends = env:main
upload_protocol = espota
upload_port = wit.local
upload_flags =
	--port=3232
	--timeout=60
	--auth="admin"

[env:spiffs-ota]
extends = env:main-ota
upload_command = pio run --target uploadfs --environment main-ota